INSERT INTO ADDTOCART (ID , COUNT ,DESCRIPTION ,PRICE , PRODUCT_NAME , RETURNABLE ,SOLD_BY) VALUES(1,12,'fitbit versa',2000,'fitbit',false,'amazon');
INSERT INTO ADDTOCART (ID , COUNT ,DESCRIPTION ,PRICE , PRODUCT_NAME , RETURNABLE ,SOLD_BY) VALUES(2,812,'apple',24000,'apple',false,'apple');
INSERT INTO ADDTOCART (ID , COUNT ,DESCRIPTION ,PRICE , PRODUCT_NAME , RETURNABLE ,SOLD_BY) VALUES(3,122,'sony earphone',12000,'sony earphone',false,'sony earphone');
INSERT INTO ADDTOWISHLIST(WISH_ID,PRICE,PRODUCT_NAME,QUANTITY,REPLACEMENT,RETURNABLE) VALUES(1,3500,'fitbit earphone',5,true,true);
INSERT INTO ADDTOWISHLIST(WISH_ID,PRICE,PRODUCT_NAME,QUANTITY,REPLACEMENT,RETURNABLE) VALUES(2,200,'sony earphone',2,false,true);
INSERT INTO ADDTOWISHLIST(WISH_ID,PRICE,PRODUCT_NAME,QUANTITY,REPLACEMENT,RETURNABLE) VALUES(3,2000,'boat earphone',3,true,false);